version: '3'
services:

  # an authentication service
  authsvc:
    build:
      context: ../build/reva
      dockerfile: Dockerfile
    hostname: authsvc.nexus.test
    volumes:
      - ../configs/reva/authsvc.toml:/etc/revad/revad.toml
    networks:
      - ocis
