version: '3'
services:

  # a webdav service
  ocdavsvc:
    build:
      context: ../build/reva
      dockerfile: Dockerfile
    hostname: ocdavsvc.nexus.test
    volumes:
      - ../configs/reva/ocdavsvc.toml:/etc/revad/revad.toml
    networks:
      ocis:
        aliases:
          - ocdavsvc.nexus.test