version: '3'
services:

  # a webdav service
  ocssvc:
    build:
      context: ../build/reva
      dockerfile: Dockerfile
    hostname: ocssvc.nexus.test
    volumes:
      - ../configs/reva/ocssvc.toml:/etc/revad/revad.toml
    networks:
      ocis:
        aliases:
          - ocssvc.nexus.test