version: '3'
services:
  storageprovidersvc:
    build:
      context: ../build/reva
      dockerfile: Dockerfile.eosprovider
    hostname: storageprovidersvc.nexus.test
    volumes:
      - ../configs/reva/storageprovider/eos.toml:/etc/revad/revad.toml
    networks:
      # For XrootD communication to EOS MGM5
      eoscluster.cern.ch:
        aliases:
          - storageprovidersvc
      ocis:
        aliases:
          - storageprovidersvc.nexus.test

networks:
  # External network used in demo eos cluster setup 
  eoscluster.cern.ch:
    external: true