version: '3'
services:
  storageprovidersvc:
    build:
      context: ../../build/reva
      dockerfile: Dockerfile
    hostname: storageprovidersvc.nexus.test
    volumes:
      - ../../configs/reva/storageprovider/local.toml:/etc/revad/revad.toml
      - ../../examples/data:/data
    networks:
      - ocis
networks:
  ocis: