---
kind: pipeline
name: build-reva

platform:
  os: linux
  arch: amd64

workspace:
  base: /drone/scr/build/reva

steps:
- name: build
  image: golang:1.12
  commands:
  - pwd
  - "git clone git@github.com:owncloud/reva.git src/"
  - "go build -o ./cmd/revad/revad -ldflags '-X main.build=${DRONE_BUILD_NUMBER}' -a -o release/revad"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on

- name: executable
  image: golang:1.12
  commands:
  - ./release/revad --help

- name: checksum
  image: alpine
  commands:
  - apk add --no-cache coreutils
  - "sha256sum -b release/* > release/sha256sum.txt"

- name: publish
  pull: always
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "release/*"
    overwrite: true
    title: "${DRONE_TAG}"
  when:
    ref:
    - "refs/tags/**"

...
