---
kind: pipeline
name: build-reva

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.12
  commands:
  - git clone https://github.com/cs3org/reva/ ./build/reva/src/
  - go get -u golang.org/x/lint/golint
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u golang.org/x/tools/cmd/goimports
  - cd ./build/reva/src
  - go build ./...
  - go mod tidy
  - "go build -v -ldflags '-X main.build=${DRONE_BUILD_NUMBER}' -a -o ../release/revad ./cmd/revad"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on

- name: executable
  image: golang:1.12
  commands:
  - ./build/reva/release/revad -t

- name: checksum
  image: alpine
  commands:
  - apk add --no-cache coreutils
  - "sha256sum -b ./build/reva/release/* > ./build/reva/release/sha256sum.txt"

- name: publish-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "./build/reva/release/*"
    overwrite: true
    title: "${DRONE_TAG}"

...
