[core]
max_cpus = "2"

[log]
output = "stdout"
mode = "dev"
level = "debug"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
access_log = "stderr"
#tls_enabled = true
#tls_cert = "/etc/gridsecurity/host.cert"
#tls_key = "/etc/gridsecurity/host.key"
enabled_services = ["authsvc"]
enabled_interceptors = ["auth", "prometheus", "log", "trace"]


[grpc.interceptors.trace]
priority = 100
header = "x-trace"

[grpc.interceptors.log]
priority = 200

[grpc.interceptors.prometheus]
priority = 300

[grpc.interceptors.auth]
priority = 400
# TODO grpc 'headers' are stored as google.golang.org/grpc/metadata ... needs better naming, this is too confusing
# keys for grpc metadata are always lowercase, so interceptors headers need to use lowercase.
header = "x-access-token"
token_strategy = "header"
token_manager = "jwt"
# GenerateAccessToken contains the credentials in the payload. Skip auth, otherwise services cannot obtain a token.
skip_methods = ["/cs3.authv0alpha.AuthService/GenerateAccessToken"]

[grpc.interceptors.auth.token_strategies.header]
header = "X-Access-Token"

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"


[grpc.services.authsvc]
auth_manager = "ldap"
token_manager = "jwt"
user_manager = "ldap"

#[grpc.services.authsvc.token_managers]
#driver = "jwt"

[grpc.services.authsvc.token_managers.jwt]
secret = "Pive-Fumkiu4"

[grpc.services.authsvc.auth_managers.ldap]
hostname = "openldap"
port = 636
base_dn = "dc=owncloudqa,dc=com"
filter = "(&(objectclass=inetorgperson)(uid=%s))"
bind_username = "cn=admin,dc=owncloudqa,dc=com"
bind_password = "admin"

[grpc.services.authsvc.user_managers.ldap]
hostname = "openldap"
port = 636
base_dn = "dc=owncloudqa,dc=com"
filter = "(&(objectclass=inetorgperson)(uid=%s))"
bind_username = "cn=admin,dc=owncloudqa,dc=com"
bind_password = "admin"
